jobs:
  release:
    permissions:
      contents: write
      id-token: write
    uses: SonarSource/gh-action_release/.github/workflows/main.yaml@v5
    with:
      slackChannel: squad-ide-intellij-family
name: sonar-release
on:
  repository_dispatch:
    types: trigger-ga___release.yml
